# Copyright 2019 TriggerMesh, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: nodejs-openfaas-runtime
spec:
  inputs:
    params:
    - name: IMAGE
      description: The URI of the image to push, including registry host
    - name: DIRECTORY
      description: The subdirectory of the workspace/repo
      default: "."
    - name: HANDLER
      description: The name of js file where handler function located
      default: handler.js
    resources:
    - name: sources
      type: git
      targetPath: /workspace
  steps:
  - name: dockerfile
    image: gcr.io/kaniko-project/executor:debug-v0.8.0
    command:
    - /busybox/sh
    args:
    - -c
    - |
      cd /workspace/workspace
      cat <<EOF > Dockerfile
        FROM alpine:3.7
        RUN apk --update add nodejs nodejs-npm

        RUN apk --no-cache add curl \
            && curl -sL https://github.com/openfaas/faas/releases/download/0.9.6/fwatchdog > /usr/bin/fwatchdog \
            && chmod +x /usr/bin/fwatchdog

        COPY . .
        RUN npm i
        ENV fprocess="node $(inputs.params.HANDLER)"
        
        CMD ["fwatchdog"]
      EOF
  - name: export
    image: gcr.io/kaniko-project/executor:debug-v0.8.0
    args:
    - --context=/workspace/workspace/$(inputs.params.DIRECTORY)
    - --dockerfile=Dockerfile
    - --destination=$(inputs.params.IMAGE)
    # Workaround not to use default config which requires gcloud credentials 
    # to pull base image from public gcr registry 
    # https://groups.google.com/d/msg/kaniko-users/r5yoP_Ejm_c/ExoEXksDBAAJ
    env:
    - name: DOCKER_CONFIG
      value: "/"